import type { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'fraud-detection-mlops',
    title: 'FRAUD DETECTION MLOPS',
    subtitle: 'End-to-end ML pipeline for real-time transaction fraud scoring',
    domain: ['ML / AI', 'Data Engineering'],
    description: 'Production-grade fraud detection system built on IEEE-CIS Kaggle dataset. XGBoost model deployed via FastAPI + Docker on AWS SageMaker with full CI/CD pipeline, MLflow experiment tracking, and real-time scoring API.',
    longDescription: `Built a complete MLOps pipeline for transaction fraud detection. The system ingests raw transaction data, engineers features, trains an XGBoost classifier, and deploys it as a low-latency REST API. Flagged over $4.2M in high-risk transactions across 28,000+ records in production.\n\nThe architecture uses AWS SageMaker for model training and hosting, MLflow for experiment tracking and model registry, FastAPI for the scoring endpoint, and Docker for containerization. GitHub Actions drives CI/CD from commit to deployment.`,
    tech: ['Python', 'XGBoost', 'FastAPI', 'Docker', 'AWS SageMaker', 'MLflow', 'GitHub Actions', 'Scikit-learn'],
    metrics: [
      { label: 'Fraud Flagged', value: '$4.2M', color: 'cyan' },
      { label: 'Transactions Analyzed', value: '28K+', color: 'orange' },
      { label: 'Manual Retraining Reduction', value: '40%', color: 'violet' },
      { label: 'Model AUC', value: '0.94', color: 'yellow' },
    ],
    githubUrl: 'https://github.com/sriramsripada20s/fraud-detection-mlops',
    featured: true,
    year: '2024',
  },
  {
    id: '2',
    slug: 'snowflake-cortex-ai-agent',
    title: 'SNOWFLAKE CORTEX AI AGENT',
    subtitle: 'Conversational BI powered by Snowflake Cortex + Claude LLM',
    domain: ['ML / AI', 'Analytics'],
    description: 'Built a natural-language BI agent integrating Snowflake Cortex with Claude LLM via LangChain. Business users query dashboards in plain English — the agent translates to SQL, executes on Snowflake, and returns insights in seconds.',
    longDescription: `Designed and deployed a conversational analytics platform at MyBambu that eliminated BI bottlenecks for non-technical teams. The agent uses Snowflake Cortex as the foundation, wired to Claude LLM through a LangChain orchestration layer.\n\nUsers type questions like "What was our highest churn segment last quarter?" and receive instant chart-ready answers. Reduced insight turnaround time by 25-65% across business teams.`,
    tech: ['Snowflake Cortex', 'Claude LLM', 'LangChain', 'Python', 'FastAPI', 'Snowflake', 'SQL'],
    metrics: [
      { label: 'Insight Turnaround Reduction', value: '65%', color: 'cyan' },
      { label: 'Teams Unblocked', value: '4+', color: 'orange' },
      { label: 'Query Accuracy', value: '92%', color: 'violet' },
    ],
    featured: true,
    year: '2024',
  },
  {
    id: '3',
    slug: 'customer-360-dbt-snowflake',
    title: 'CUSTOMER 360 PLATFORM',
    subtitle: 'dbt medallion architecture on Snowflake — 5M+ daily records',
    domain: ['Data Engineering', 'Analytics'],
    description: 'End-to-end customer segmentation and RFM analytics platform. dbt medallion architecture (Bronze → Silver → Gold) processes 5M+ daily records on Snowflake with full data contracts, automated tests, and CI/CD via GitHub Actions.',
    longDescription: `Designed the complete data platform at MyBambu from scratch. The pipeline ingests raw transaction, event, and customer data into Snowflake's Bronze layer, applies transformations and business logic in Silver, and exposes analytics-ready Gold tables for BI consumption.\n\ndbt models include over 120 tests, full column-level documentation, data contracts, and incremental loading patterns. GitHub Actions runs CI on every PR — blocking merges if tests fail.`,
    tech: ['dbt', 'Snowflake', 'GitHub Actions', 'Python', 'SQL', 'Sigma', 'Power BI'],
    metrics: [
      { label: 'Daily Records Processed', value: '5M+', color: 'cyan' },
      { label: 'dbt Models', value: '40+', color: 'orange' },
      { label: 'Dashboard Performance Gain', value: '30%', color: 'violet' },
      { label: 'Data Tests', value: '120+', color: 'yellow' },
    ],
    featured: true,
    year: '2023',
  },
  {
    id: '4',
    slug: 'churn-prediction-model',
    title: 'CHURN PREDICTION MODEL',
    subtitle: '85% accuracy customer churn model for fintech neobank',
    domain: ['ML / AI'],
    description: 'Supervised ML model predicting customer churn 30 days ahead with 85% accuracy. Built on Snowpark ML, integrating directly with the Snowflake data warehouse. Outputs feed into automated retention campaigns.',
    longDescription: `Trained a gradient boosted classifier on historical customer behavior, transaction patterns, and engagement signals from the Bambu Pay platform. Feature engineering was done in dbt; model training and inference run inside Snowflake via Snowpark Python.\n\nModel outputs are written back to Snowflake Gold tables and consumed by marketing automation for targeted retention campaigns.`,
    tech: ['Python', 'Snowpark ML', 'Snowflake', 'dbt', 'XGBoost', 'scikit-learn', 'MLflow'],
    metrics: [
      { label: 'Model Accuracy', value: '85%', color: 'cyan' },
      { label: 'Prediction Horizon', value: '30 days', color: 'orange' },
      { label: 'Features Engineered', value: '60+', color: 'violet' },
    ],
    featured: false,
    year: '2023',
  },
  {
    id: '5',
    slug: 'nlp-topic-modeling-pipeline',
    title: 'NLP TOPIC MODELING',
    subtitle: 'Unsupervised Gensim LDA pipeline on AWS SageMaker',
    domain: ['ML / AI', 'Data Engineering'],
    description: 'Fully automated NLP topic modeling pipeline on AWS SageMaker using Gensim LDA. Scheduled via EventBridge, monitored with CloudWatch, and parameterized through SSM Parameter Store for zero-touch operation.',
    longDescription: `Built a production-ready topic modeling system that runs on a schedule without manual intervention. The pipeline pulls text data from S3, preprocesses it, fits an LDA model, and writes topic assignments back to the data lake.\n\nAll configuration lives in SSM Parameter Store — changing the number of topics or preprocessing parameters requires no code changes. CloudWatch dashboards and alarms provide full observability.`,
    tech: ['Python', 'Gensim LDA', 'AWS SageMaker', 'EventBridge', 'CloudWatch', 'SSM Parameter Store', 'S3'],
    metrics: [
      { label: 'Topics Discovered', value: '15', color: 'cyan' },
      { label: 'Pipeline Uptime', value: '99.9%', color: 'orange' },
      { label: 'Manual Ops', value: '0', color: 'violet' },
    ],
    featured: false,
    year: '2024',
  },
  {
    id: '6',
    slug: 'sigma-power-bi-dashboards',
    title: 'BI DASHBOARD SUITE',
    subtitle: 'Sigma + Power BI dashboards with RLS and live Snowflake queries',
    domain: ['BI', 'Analytics'],
    description: 'Suite of executive and operational dashboards built in Sigma Computing and Power BI. Live queries against Snowflake Gold tables with row-level security, DAX measures, and 30% performance improvement over legacy reports.',
    longDescription: `Replaced legacy Excel-based reporting with a modern BI layer at MyBambu. Sigma dashboards leverage Snowflake's compute directly — no data extracts, always fresh. Power BI models use DirectQuery with incremental refresh and dynamic RLS tied to user roles.\n\nKey dashboards include: Executive KPIs, Transaction Analytics, Customer Segmentation, Fraud Operations, and Churn Monitoring.`,
    tech: ['Sigma Computing', 'Power BI', 'DAX', 'Snowflake', 'SQL', 'dbt Metrics'],
    metrics: [
      { label: 'Dashboard Performance', value: '+30%', color: 'cyan' },
      { label: 'Dashboards Delivered', value: '12', color: 'orange' },
      { label: 'Report Turnaround', value: '-65%', color: 'violet' },
    ],
    featured: false,
    year: '2023',
  },
];
