import type { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'fraud-detection-mlops',
    title: 'FRAUD DETECTION MLOPS',
    subtitle: 'End-to-end ML pipeline for real-time transaction fraud scoring',
    domain: ['ML / AI', 'Data Engineering'],
    description: 'Production-grade fraud detection system built on IEEE-CIS Kaggle dataset. XGBoost model deployed via FastAPI + Docker on AWS SageMaker with full CI/CD pipeline, MLflow experiment tracking, and real-time scoring API.',
    longDescription: `Built a complete MLOps pipeline for transaction fraud detection. The system ingests raw transaction data, engineers features, trains an XGBoost classifier, and deploys it as a low-latency REST API. Flagged over $4.2M in high-risk transactions across 28,000+ records in production.\n\nThe architecture uses AWS SageMaker for model training and hosting, MLflow for experiment tracking and model registry, FastAPI for the scoring endpoint, and Docker for containerization. GitHub Actions drives CI/CD from commit to deployment.`,
    tech: ['Python', 'XGBoost', 'FastAPI', 'Docker', 'AWS SageMaker', 'MLflow', 'GitHub Actions', 'Scikit-learn'],
    metrics: [
      { label: 'Fraud Flagged', value: '$4.2M', color: 'cyan' },
      { label: 'Transactions Analyzed', value: '28K+', color: 'orange' },
      { label: 'Manual Retraining Reduction', value: '40%', color: 'violet' },
      { label: 'Model AUC', value: '0.94', color: 'yellow' },
    ],
    githubUrl: 'https://github.com/sriramsripada20s/fraud-detection-mlops',
    featured: true,
    year: '2024',
  },
  {
    id: '2',
    slug: 'snowflake-cortex-ai-agent',
    title: 'SNOWFLAKE CORTEX AI AGENT',
    subtitle: 'Conversational BI powered by Snowflake Cortex + Claude LLM',
    domain: ['ML / AI', 'Analytics'],
    description: 'Built a natural-language BI agent integrating Snowflake Cortex with Claude LLM via LangChain. Business users query dashboards in plain English — the agent translates to SQL, executes on Snowflake, and returns insights in seconds.',
    longDescription: `Designed and deployed a conversational analytics platform at MyBambu that eliminated BI bottlenecks for non-technical teams. The agent uses Snowflake Cortex as the foundation, wired to Claude LLM through a LangChain orchestration layer.\n\nUsers type questions like "What was our highest churn segment last quarter?" and receive instant chart-ready answers. Reduced insight turnaround time by 25-65% across business teams.`,
    tech: ['Snowflake Cortex', 'Claude LLM', 'LangChain', 'Python', 'FastAPI', 'Snowflake', 'SQL'],
    metrics: [
      { label: 'Insight Turnaround Reduction', value: '65%', color: 'cyan' },
      { label: 'Teams Unblocked', value: '4+', color: 'orange' },
      { label: 'Query Accuracy', value: '92%', color: 'violet' },
    ],
    featured: true,
    year: '2024',
  },
  {
    id: '3',
    slug: 'customer-360-dbt-snowflake',
    title: 'CUSTOMER 360 PLATFORM',
    subtitle: 'dbt medallion architecture on Snowflake — 5M+ daily records',
    domain: ['Data Engineering', 'Analytics'],
    description: 'End-to-end customer segmentation and RFM analytics platform. dbt medallion architecture processes 5M+ daily records on Snowflake with full data contracts, 263 automated tests, composite scoring, and CI/CD via GitHub Actions.',
    longDescription: `A fintech neobank serving 50,000+ customers had data sitting in silos. Transactions, sessions, campaigns, and orders never talked to each other — resulting in generic marketing, reactive fraud detection, and no unified customer view.`,
    tech: ['dbt', 'Snowflake', 'Snowpipe', 'GitHub Actions', 'Python', 'Snowpark ML', 'Sigma', 'Power BI'],
    metrics: [
      { label: 'Daily Records Processed', value: '5M+', color: 'cyan' },
      { label: 'dbt Models', value: '22', color: 'orange' },
      { label: 'Automated Tests', value: '263', color: 'violet' },
      { label: 'Composite Scores', value: '3', color: 'yellow' },
    ],
    featured: true,
    year: '2024',
    sections: [
      {
        title: 'The Business Problem',
        content: 'A fintech neobank serving 50,000+ customers had data sitting in silos. Transactions, sessions, campaigns, and orders never talked to each other — resulting in generic marketing, reactive fraud detection, and no unified customer view.',
        bullets: [
          'No unified view of who each customer was',
          'Generic marketing sent to all customers equally',
          'Fraud discovered after the money was already lost',
          'Every team working from different numbers',
        ],
      },
      {
        title: 'Architecture',
        content: '5-layer medallion architecture on Snowflake — each layer with a clear purpose and strict contracts.',
        bullets: [
          'RAW — raw data landed from S3 via Snowpipe, untouched',
          'STAGING — cleaned, deduplicated, standardized with no business logic',
          'INTERMEDIATE — business joins and aggregations as ephemeral models',
          'MART — analytics-ready fact and dimension tables',
          'FEATURES — ML-ready normalized feature tables for Snowpark',
        ],
      },
      {
        title: 'Data Sources',
        content: '7 source tables ingested into Snowflake RAW via Snowpipe with Streams + Tasks for near-real-time CDC updates.',
        bullets: [
          'customers — demographics, loyalty tier, signup date',
          'orders — purchase history, channel, order status',
          'order_items — product-level detail, categories, discounts',
          'transactions — payment events, device, location',
          'events — clickstream sessions, product views, cart activity',
          'campaigns — email/push/SMS responses and conversions',
          'products — catalog, pricing, category hierarchy',
        ],
      },
      {
        title: 'dbt Models — 22 Models, 263 Tests',
        content: 'Built across 4 layers with full data contracts, column-level docs, and incremental loading patterns.',
        bullets: [
          'Staging (7 models) — one model per source, QUALIFY ROW_NUMBER() deduplication, type casting, null handling',
          'Intermediate (5 ephemeral) — RFM metrics, fraud signals, session features, payment signals, product affinity',
          'Mart (3 tables) — dim_customers, fct_orders, fct_customer_value (the Customer 360 table)',
          'Features (2 incremental) — feat_customer_segmentation and feat_fraud_behavior for ML',
        ],
      },
      {
        title: 'Customer 360 Output',
        content: 'fct_customer_value is the centrepiece — one row per customer combining all signals into three composite scores.',
        bullets: [
          'customer_value_score (0–100) — Recency 25pts + Frequency 25pts + Monetary 30pts + Engagement 20pts',
          'churn_risk_score (0–100) — Recency decline + Frequency drop + Discount dependency + Payment failures',
          'personalization_score (0–100) — How well the platform knows this customer across all data points',
          '7 fraud risk flags — geo velocity, rapid transactions, multiple cards, high chargebacks, and more',
        ],
      },
      {
        title: 'Data Quality',
        content: '263 automated tests run on every build — no model reaches production without passing.',
        bullets: [
          'not_null and unique on all primary keys across every model',
          'accepted_values on status fields, loyalty tiers, device types, payment methods',
          'relationships tests ensuring referential integrity across dims and facts',
          'Custom singular tests: assert_no_duplicate_customers, assert_no_negative_revenue',
        ],
      },
      {
        title: 'CI/CD Pipeline',
        content: 'GitHub Actions pipeline runs automatically on every push and pull request.',
        bullets: [
          'Installs dbt-snowflake and runs dbt deps on every trigger',
          'Writes profiles.yml securely from GitHub Secrets — no credentials in code',
          'Runs dbt compile first to catch syntax and ref errors without hitting Snowflake',
          'Builds all 4 layers sequentially — staging → intermediate → marts → features',
          'All 263 tests run automatically — any failure blocks the merge',
          'Artifacts (manifest.json, run_results.json) saved 7 days for debugging',
        ],
      },
    ],
  },
  {
    id: '4',
    slug: 'churn-prediction-model',
    title: 'CHURN PREDICTION MODEL',
    subtitle: '85% accuracy customer churn model for fintech neobank',
    domain: ['ML / AI'],
    description: 'Supervised ML model predicting customer churn 30 days ahead with 85% accuracy. Built on Snowpark ML, integrating directly with the Snowflake data warehouse. Outputs feed into automated retention campaigns.',
    longDescription: `Trained a gradient boosted classifier on historical customer behavior, transaction patterns, and engagement signals from the Bambu Pay platform. Feature engineering was done in dbt; model training and inference run inside Snowflake via Snowpark Python.\n\nModel outputs are written back to Snowflake Gold tables and consumed by marketing automation for targeted retention campaigns.`,
    tech: ['Python', 'Snowpark ML', 'Snowflake', 'dbt', 'XGBoost', 'scikit-learn', 'MLflow'],
    metrics: [
      { label: 'Model Accuracy', value: '85%', color: 'cyan' },
      { label: 'Prediction Horizon', value: '30 days', color: 'orange' },
      { label: 'Features Engineered', value: '60+', color: 'violet' },
    ],
    featured: false,
    year: '2023',
  },
  {
    id: '5',
    slug: 'nlp-topic-modeling-pipeline',
    title: 'NLP TOPIC MODELING',
    subtitle: 'Unsupervised Gensim LDA pipeline on AWS SageMaker',
    domain: ['ML / AI', 'Data Engineering'],
    description: 'Fully automated NLP topic modeling pipeline on AWS SageMaker using Gensim LDA. Scheduled via EventBridge, monitored with CloudWatch, and parameterized through SSM Parameter Store for zero-touch operation.',
    longDescription: `Built a production-ready topic modeling system that runs on a schedule without manual intervention. The pipeline pulls text data from S3, preprocesses it, fits an LDA model, and writes topic assignments back to the data lake.\n\nAll configuration lives in SSM Parameter Store — changing the number of topics or preprocessing parameters requires no code changes. CloudWatch dashboards and alarms provide full observability.`,
    tech: ['Python', 'Gensim LDA', 'AWS SageMaker', 'EventBridge', 'CloudWatch', 'SSM Parameter Store', 'S3'],
    metrics: [
      { label: 'Topics Discovered', value: '15', color: 'cyan' },
      { label: 'Pipeline Uptime', value: '99.9%', color: 'orange' },
      { label: 'Manual Ops', value: '0', color: 'violet' },
    ],
    featured: false,
    year: '2024',
  },
  {
    id: '6',
    slug: 'sigma-power-bi-dashboards',
    title: 'BI DASHBOARD SUITE',
    subtitle: 'Sigma + Power BI dashboards with RLS and live Snowflake queries',
    domain: ['BI', 'Analytics'],
    description: 'Suite of executive and operational dashboards built in Sigma Computing and Power BI. Live queries against Snowflake Gold tables with row-level security, DAX measures, and 30% performance improvement over legacy reports.',
    longDescription: `Replaced legacy Excel-based reporting with a modern BI layer at MyBambu. Sigma dashboards leverage Snowflake's compute directly — no data extracts, always fresh. Power BI models use DirectQuery with incremental refresh and dynamic RLS tied to user roles.\n\nKey dashboards include: Executive KPIs, Transaction Analytics, Customer Segmentation, Fraud Operations, and Churn Monitoring.`,
    tech: ['Sigma Computing', 'Power BI', 'DAX', 'Snowflake', 'SQL', 'dbt Metrics'],
    metrics: [
      { label: 'Dashboard Performance', value: '+30%', color: 'cyan' },
      { label: 'Dashboards Delivered', value: '12', color: 'orange' },
      { label: 'Report Turnaround', value: '-65%', color: 'violet' },
    ],
    featured: false,
    year: '2023',
  },
];
